# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins: []

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "TSUZUKU — Japanese Experience"

# Avatar image path
avatar: "/assets/logo.png"

# Name section text
name: "@TSUZUKU"

# Tagline section text
tagline: >-
    TSUZUKU offers drinks and light meals in organic form without any artificial additives or syrups.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-globe"
      text: "Website"
      url: "https://www.tsuzuku-sa.com"
      alt: "TSUZUKU official website"
      title: "TSUZUKU official website"
      target: "_blank"
  - link:
      icon: "fa-solid fa-mug-saucer"
      text: "Menu / Blog"
      url: "https://www.tsuzuku-sa.com/blog"
      alt: "TSUZUKU menu and blog"
      title: "TSUZUKU menu and blog"
      target: "_blank"
  - link:
      icon: "fa-brands fa-whatsapp"
      text: "Order on WhatsApp — 055 581 5489"
      url: "https://wa.me/966555815489"
      alt: "WhatsApp order for TSUZUKU"
      title: "Order on WhatsApp"
      target: "_blank"
  - link:
      icon: "fa-solid fa-phone"
      text: "Call Us — 055 581 5489"
      url: "tel:+966555815489"
      alt: "Call TSUZUKU"
      title: "Call TSUZUKU"
      target: "_self"
  - link:
      icon: "fa-solid fa-location-dot"
      text: "Find Us on Google Maps"
      url: "https://maps.app.goo.gl/oUgmqNJYah5byHFa7"
      alt: "TSUZUKU location on Google Maps"
      title: "TSUZUKU location on Google Maps"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "YouTube"
      url: "https://www.youtube.com/@TsuzukuSA"
      alt: "TSUZUKU YouTube channel"
      title: "TSUZUKU YouTube channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://www.instagram.com/tsuzuku.sa/"
      alt: "TSUZUKU on Instagram"
      title: "TSUZUKU on Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-tiktok"
      text: "TikTok"
      url: "https://www.tiktok.com/@tsuzuku_sa"
      alt: "TSUZUKU on TikTok"
      title: "TSUZUKU on TikTok"
      target: "_blank"
  - link:
      icon: "fa-brands fa-x-twitter"
      text: "X (Twitter)"
      url: "https://x.com/Tsuzuku_SA"
      alt: "TSUZUKU on X (Twitter)"
      title: "TSUZUKU on X (Twitter)"
      target: "_blank"
  - link:
      icon: "fa-brands fa-snapchat"
      text: "Snapchat"
      url: "https://www.snapchat.com/add/tsuzuku.co"
      alt: "TSUZUKU on Snapchat"
      title: "TSUZUKU on Snapchat"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-whatsapp"
      url: "https://wa.me/966555815489"
      title: "WhatsApp"
      alt: "WhatsApp"
      target: "_blank"
  - social:
      icon: "fa-solid fa-phone"
      url: "tel:+966555815489"
      title: "Call"
      alt: "Call"
      target: "_self"
  - social:
      icon: "fa-solid fa-location-dot"
      url: "https://maps.app.goo.gl/oUgmqNJYah5byHFa7"
      title: "Google Maps"
      alt: "Google Maps"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@TsuzukuSA"
      title: "YouTube"
      alt: "YouTube"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/tsuzuku.sa/"
      title: "Instagram"
      alt: "Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-tiktok"
      url: "https://www.tiktok.com/@tsuzuku_sa"
      title: "TikTok"
      alt: "TikTok"
      target: "_blank"
  - social:
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/Tsuzuku_SA"
      title: "X (Twitter)"
      alt: "X (Twitter)"
      target: "_blank"
  - social:
      icon: "fa-brands fa-snapchat"
      url: "https://www.snapchat.com/add/tsuzuku.co"
      title: "Snapchat"
      alt: "Snapchat"
      target: "_blank"
  - social:
      icon: "fa-solid fa-globe"
      url: "https://www.tsuzuku-sa.com"
      title: "Website"
      alt: "Website"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:info@tsuzuku-sa.com"
      title: "Email: info@tsuzuku-sa.com"
      alt: "info@tsuzuku-sa.com"
      target: "_blank"

# Footer text
footer: >
    Welcome to TSUZUKU.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
    © 2025 TSUZUKU
